env:
  browser: true
  es6: true
extends:
  - standard
globals:
  $: readonly
  triggerLineAction: writeable
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {}
